/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vless_MainActivity */

#ifndef _Included_com_vless_MainActivity
#define _Included_com_vless_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vless_MainActivity
 * Method:    getIntC2Java
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vless_MainActivity_getIntC2Java
  (JNIEnv *, jobject);

/*
 * Class:     com_vless_MainActivity
 * Method:    C2Java
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vless_MainActivity_C2Java
  (JNIEnv *, jobject);

/*
 * Class:     com_vless_MainActivity
 * Method:    SC2Java
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vless_MainActivity_SC2Java
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
